version: '3.8'

volumes:
  postgres-data:
  cargo:
  rustup:

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Use the VARIANT arg to pick a Debian OS version: buster, bullseye
        # Use bullseye when on local on arm64/Apple Silicon.
        VARIANT: bullseye
        CARGO_HOME: /usr/local/cargo
        RUSTUP_HOME: /usr/local/rustup
    env_file:
      - .env
    command: sleep infinity
    network_mode: service:db
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    volumes:
      - ../..:/workspace:cached
      - cargo:/usr/local/cargo
      - rustup:/usr/local/rustup
    deploy:
      resources:
        limits:
          memory: 25G
  db:
    image: postgres:14-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PG_DATA=/var/lib/progresql/data
    volumes:
      - postgres-data:/var/lib/progresql/data
